server:
  port: 8888
  error:
    whitelabel:
      enabled: true

trace: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
    ru.reinform.security.opa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: policy-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      metrics:
        enabled: true
      routes:
        - id: resource
          uri: "http://localhost:9000/"
          predicates:
            - Path=/resource
          filters:
            - SetPath=/resource
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: hello
          uri: "http://localhost:9010/"
          predicates:
            - Path=/hello
          filters:
            - SetPath=/hello
            #- RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: meeting-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/meetings
          filters:
            - SetPath=/meetings
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: executor-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/executors
          filters:
            - SetPath=/executors
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: assignment-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/assignments
          filters:
            - SetPath=/assignments
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory

      default-filters:
        - TokenRelay

opa:
  url: http://localhost:8181/v1/data/authz/authorized
