server:
  port: 8888
  error:
    whitelabel:
      enabled: true

trace: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
    ru.reinform.security.opa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: policy-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak2:
            provider: keycloak
            client-id: smart-gateway
            client-secret: 9Nu9ar5UPT7VB0tTmMRFQSX0WLQopq3q
            scope:
              - openid
              - profile
              - email
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/ng

        provider:
          keycloak:
            issuer-uri: http://localhost:3000/iam/auth/realms/demo
            token-uri: http://localhost:3000/iam/auth/realms/demo/protocol/openid-connect/token
            authorization-uri: http://localhost:3000/iam/auth/realms/demo/protocol/openid-connect/auth
            user-info-uri: http://localhost:3000/iam/auth/realms/demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      metrics:
        enabled: true
      routes:
        - id: resource
          uri: "http://localhost:9000/"
          predicates:
            - Path=/resource
          filters:
            - SetPath=/resource
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: hello
          uri: "http://localhost:9000/"
          predicates:
            - Path=/hello
          filters:
            - SetPath=/hello
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: meeting-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/meetings
          filters:
            - SetPath=/meetings
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: executor-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/executors
          filters:
            - SetPath=/executors
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory
        - id: assignment-list
          uri: "http://localhost:9000/"
          predicates:
            - Path=/assignments
          filters:
            - SetPath=/assignments
            - RemoveRequestHeader=Cookie
            - RequestPolicyFilterFactory

      default-filters:
        - TokenRelay

opa:
  url: http://localhost:8181/v1/data/authz/authorized
