decision_logs:
  console: true

services:
  - name: bunble-server
    url: http://localhost:8081

bundles:
  rbac:
    service: bunble-server
    resource: bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 300
