decision_logs:
  console: true

services:
  - name: bunble-server
    url: http://localhost:8080

bundles:
  authz:
    service: bunble-server
    resource: data.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
