opa:
  bundle:
    revision: 0.0.1
    roots:
      - name: "authz"
        targets:
          - target: authz/data.json
            type: resource
            uri:  authz/data.json
          - target: authz/policy.rego
            type: resource
            uri:  authz/policy.rego
#         - target: authz/policy.rego
#           type: file
#           uri: /home/valery/IdeaProjects/github.com/vgryzunov/smart-gateway/bundle-server/opa/debug.rego
      - name: "certs"
        targets:
          - target: certs/data.json
            type: http
            uri: https://keycloak.192.168.49.2.nip.io/iam/auth/realms/demo/protocol/openid-connect/certs

